[uwsgi]
strict = true
die-on-term = true
need-app = true
single-interpreter = true

workers = 2
master = true

http = 0.0.0.0:8880

module = dmarcwebui:app
procname-prefix = dmarc-testing-

py-autoreload = 1
thunder-lock = true

# cpu-afinity
